---
title: "House Price Dataset Exploration"
author: "newbiettn"
date: "3 February 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##

```{r}
library(VIM) #aggr
library(Amelia) #missmap
```

## Data loading

```{r}
train_raw <- read.csv("data/train.csv", na.strings = c("NA", ""))

# Back up
train <- train_raw
```

```
str(train)

indx <- c("MSSubClass", "OverallQual", "OverallCond", "YearBuilt", "YearRemodAdd",
          "BsmtFullBath", "BsmtHalfBath", "FullBath", "HalfBath", "BedroomAbvGr",
          "KitchenAbvGr", "TotRmsAbvGrd", "Fireplaces")
train[indx] <- lapply(train[indx], as.character)
```

```{r}
aggr(train, col=c('navyblue','red'), numbers=TRUE, 
                     sortVars=TRUE, labels=names(train), cex.axis=.7, gap=3, 
                     ylab=c("Histogram of missing data","Pattern"))

missmap(train)
```

Features PoolQC, MiscFeature, Alley, Fence and FireplaceQu have >40% missing, thus, we have to remove all of them.

```{r}
train[]
```
